#!/bin/sh /etc/rc.common
# (C) 2013 openwrt.org

START=99
USE_PROCD=1
NAME=crowdsec-firewall-bouncer
PROG=/usr/bin/crowdsec-firewall-bouncer
CONFIG=/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml

boot()
{
	rc_procd start_service
}

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" -c "$CONFIG"
	procd_close_instance
}

reload_service() {
	procd_send_signal $PROG
}

stop_service()
{
	rc_procd killall "$PROG"
}
